### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project keywhiz-testing

### ISSUE THREAD

**Issue by lilianwen** [square/keywhiz#405] opened 2019-04-18 07:03 UTC
master
OS： centos7.4
command:  mvn install -P h2
error as below
![微信截图_20190418150159](https://user-images.githubusercontent.com/16525370/56342629-19d35580-61eb-11e9-9df5-d64a30b01a18.png)

**Comment by csstaub** [comment] 2019-04-18 18:09
Hi @lilianwen, can you provide us with the full build log to debug? Ideally as a txt file?

**Comment by lilianwen** [comment] 2019-04-19 03:17
> Hi @lilianwen, can you provide us with the full build log to debug? Ideally as a txt file?
as you wish.

[log.txt](https://github.com/square/keywhiz/files/3096892/log.txt)

**Comment by mbyczkowski** [comment] 2019-08-03 04:43
Cannot reproduce - this was either fixed in 3.8.1 or was due to the state of maven deps (i.e. needed `mvn clean` before running `mvn install` again).

**Closed by mbyczkowski** 2019-08-03 04:43 UTC
